 
{{ config(materialized='table') }}

with PLAYGROUND_DIMPLE_KUDANANI_LOCS as (
    SELECT 
TIME_ZONE,
LATITUDE,	
LOCATION_ISO_CODE,		
TOTAL_REGENCIES,	
POPULATION_DENSITY,
POPULATION,
NEW_DEATHS_PER_MILLION,
NEW_RECOVERED,
CASE_FATALITY_RATE,
NEW_DEATHS,
TOTAL_CITIES,
TOTAL_DISTRICTS,
TOTAL_DEATHS,
ISLAND,
LONGITUDE,
DATE,
PROVINCE,
CASE_RECOVERED_RATE,
CONTINENT,
TOTAL_DEATHS_PER_MILLION,
LOCATION_LEVEL,	
LOCATION,
_FIVETRAN_SYNCED

from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_DIMPLE_KUDANANI"
),

final as (

select *
from
 PLAYGROUND_DIMPLE_KUDANANI_LOCS

)

select * from final

